name: Generate Changelog
   
on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install auto-changelog
        run: npm install -g auto-changelog
      
      - name: Generate changelog
        run: auto-changelog --output HISTORY.md --template keepachangelog
      
      - name: Commit changelog
        run: |
          git config --local user.email "liaqatsaeed007@gmail.com"
          git config --local user.name "Liaqat Saeed"
          git add HISTORY.md
          git commit -m "Update changelog"
          git push
