name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npx release-it
